### ISSUE TITLE
Passing script args to single command actions fails

### ISSUE THREAD

**Issue by ilg-ul** [xpack/xpm-js#141]
### Discussed in https://github.com/xpack/xpm-js/discussions/140

<div type='discussions-op-text'>

<sup>Originally posted by **aaronf-at-d5** June 15, 2022</sup>
Note: If this is not the correct place for this question, I can move it.  I checked out Tapatalk but it says the forum is deprecated in favor of GitHub Discussions and the threads appear locked.  There is nothing else posted here, so hopefully this is the correct place.

The synopsis for xpm run is:  
`xpm run [options...] [<command>] [-- <script args>]`

I would like to be able to pass extra optional arguments to the CMake and/or Ninja commands directly from the command line.  I have tried everything I can to get `<script args>` to pass through, but no matter what I do I get "error: optional arguments not supported for array of commands"

I have tried having the action defined in both the `scripts` and the `actions` properties.  I have made sure that the elements are not JSON arrays (i.e. no opening or closing square brackets).  I have tried `xpm run-script` in place of `xpm run`.  I'm not understanding how we pass extra parameters to the underlying commands without having all possible permutations spelled out in the `package.json`.

For example, in the Hello World Quick Start template, we have a single `test` command under `scripts`.  I tried testing with this:  
```
$ xpm run test -- "testing"
error: optional arguments not supported for array of commands

$ xpm run-script test -- "testing"
error: optional arguments not supported for array of commands
```

Also, the `clean` command of both the Debug and Release configurations is a single command and not an array of commands.  This also does not work:  
```
$ xpm run clean --config Debug -- "testing"
error: optional arguments not supported for array of commands
```

What am I missing?</div>

**Comment by aaronf-at-d5** [comment]
Hi Liviu,

Thanks for the quick response on this.  Can you verify: I'm guessing my experiments with the Hello World template should not have gotten the errors shown above?

**Comment by ilg-ul** [comment]
Hi Aaron,

Please install 0.13.6 with:

```console
npm install --global xpm@next
```

and test it in your environment.

**Comment by aaronf-at-d5** [comment]
Checking now.  I got an EPERM error running `npm install --global xpm@next`.  I tried running from Administrator mode cmd.exe shell and closing down apps but am still getting the same error.  `xpm` is now not found in the path.  I'm going to try some other things here or possibly switch over to WSL.

**Comment by aaronf-at-d5** [comment]
Verified in WSL.  It's working!

**Comment by ilg-ul** [comment]
> Verified in WSL. It's working!

Great! Thank you for confirming.

However, you did something wrong, since xpm should never be installed with Administrator rights.

I suggest you review the installation page, remove everything and install properly, without admin rights.

**Comment by aaronf-at-d5** [comment]
Ok, yeah, I did something on the Windows side.  I'll review the installation page.  Thank you!
