### ISSUE TITLE
general question template

### ISSUE THREAD

**Issue by tdjastrzebski** [xpack/xpm-js#146]
When one tries to open a new issue as a general question the template says:
`If you have any other topics that are not bugs or feature requests, they are welcomed in the project forums on [Tapatalk](https://www.tapatalk.com/groups/xpack/), the **xpm** section.`

However, https://www.tapatalk.com/groups/xpack site states:  
`Information: This forum is now DEPRECATED in favour of GitHub Discussions!`

It may be a good idea to update the template.

**Comment by ilg-ul** [comment]
Thank you, Tomasz, for spotting this.

Fixed.
