### ISSUE TITLE
Listing package in the root folder fails

### ISSUE THREAD

**Issue by ilg-ul** [xpack/xpm-js#165]
As reported by Tommy Murphy @TommyMurphyTM1234:

> From: Tommy Murphy <...>
> Subject: More Windows xpm strangeness?
> Date: 18 May 2023 at 01:00:03 EEST
>
> Why do things fail in root (C:\)?
>
> C:\>xpm list --global
> EPERM: operation not permitted, mkdir 'C:\'

**Comment by ilg-ul** [comment]
Fixed on 2023-05-18, with a new version of cli-start-options.

**Comment by TommyMurphyTM1234** [comment]
Just to confirm that 0.15.1 addresses the issue for me - thanks.
