### ISSUE TITLE
Slightly arcane error message when xPack store does not exist

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [xpack/xpm-js#166]
I got the following after installing Node/npm/xpm on a clean machine and before downloading anything to the global store:
```
# Windows
xpm list --global
error: Error: ENOENT: no such file or directory, scandir 'C:\Users\Tommy Murphy\AppData\Roaming\xPacks'

# Linux
xpm list --global
error: Error: ENOENT: no such file or directory, scandir '/home/tommy/.local/xPacks'
```
The error message could/should probably be friendlier?

I'm not sure if this also applies in other contexts - system store? project private store?

**Comment by ilg-ul** [comment]
The recursive code used to enumerate the packages did not check if the folder is present.

I added the code to create the folder and the error is no longer thrown.

**Comment by ilg-ul** [comment]
Fixed on 2023-05-23.
