### ISSUE TITLE
On Windows, meson doesn't support the .cmd stubs to individual programs added in xpacks/.bin

### ISSUE THREAD

**Issue by pur-jus** [xpack/xpm-js#169]
## Describe the bug

In case of we use Meson for a cross-compilation (build machine = Win10, host machine = RISC-V) the links to individual programs added in xpacks/.bin (or .cmd stubs on Windows) during a `xpm install` aren't supported basically.

During the `meson setup --cross-file riscv.crossfile build_folder` command through a `xpm run prepare` command, Meson doesn't find the binaries listed into the Meson cross build definition file (`riscv.crossfile`).

## To Reproduce

Steps to reproduce the behaviour:

1) `xpm install`
2) `xpm run prepare --config Debug`

```powershell
❯ xpm run prepare --config Debug
> meson setup --cross-file riscv.crossfile 10_Builds\Meson\debug
The Meson build system
Version: 0.63.3
Source dir: C:\dev\riscv-disco\my_project
Build dir: C:\dev\riscv-disco\my_project\10_Builds\Meson\debug
Build type: cross build
Project name: my_project
Project version: 0.1

meson.build:1:0: ERROR: Unknown compiler(s): [['riscv-none-elf-gcc']]
The following exception(s) were encountered:
Running `riscv-none-elf-gcc --version` gave "[WinError 2] The system cannot find the file specified"

A full log can be found at C:\dev\riscv-disco\my_project\10_Builds\Meson\debug\meson-logs\meson-log.txt
error: running 'meson setup --cross-file riscv.crossfile 10_Builds\Meson\debug' failed
```

3) Add `.cmd` extension at the end of all binaries files of the list of the binaries into the Meson cross build definition file.

```meson
[binaries]
c       = 'riscv-none-elf-gcc.cmd'
cpp     = 'riscv-none-elf-g++.cmd'
ld      = 'riscv-none-elf-ld.cmd'
ar      = 'riscv-none-elf-ar.cmd'
as      = 'riscv-none-elf-gcc.cmd -x assembler-with-cpp'
size    = 'riscv-none-elf-size.cmd'
objdump = 'riscv-none-elf-objdump.cmd'
objcopy = 'riscv-none-elf-objcopy.cmd'
strip   = 'riscv-none-elf-strip.cmd'
gdb     = 'riscv-none-elf-gdb.cmd'

[host_machine]
system     = 'none'
cpu_family = 'riscv32'
cpu        = 'rv32imc'
endian     = 'little'
```

4) `xpm run prepare --config Debug`

```powershell
❯ xpm run prepare --config Debug
> meson setup --cross-file riscv.crossfile 10_Builds\Meson\debug
The Meson build system
Version: 0.63.3
Source dir: C:\dev\riscv-disco\my_project
Build dir: C:\dev\riscv-disco\my_project\10_Builds\Meson\debug
Build type: cross build
Project name: my_project
Project version: 0.1
C compiler for the host machine: riscv-none-elf-gcc.cmd (gcc 12.2.0 "riscv-none-elf-gcc.exe (xPack GNU RISC-V Embedded GCC x86_64) 12.2.0")
C linker for the host machine: riscv-none-elf-gcc.cmd ld.bfd 2.38
C compiler for the build machine: gcc (gcc 8.1.0 "gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0")
C linker for the build machine: gcc ld.bfd 2.30
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: riscv32
Host machine cpu: rv32imc
Target machine cpu family: riscv32
Target machine cpu: rv32imc
Message: C compiler version: 12.2.0
Program riscv-none-elf-objcopy.cmd found: YES
Program riscv-none-elf-objdump.cmd found: YES
Program riscv-none-elf-size.cmd found: YES
Program riscv-none-elf-gdb.cmd found: YES
Build targets in project: 2

my_project 0.1

  User defined options
    Cross files: riscv.crossfile

Found ninja-1.11.1 at C:\dev\riscv-disco\my_project\xpacks\.bin\ninja.CMD
```

## Expected behaviour

Don't add a `.cmd` extension at the end of all binary files of the list of the binaries into the Meson cross build definition file to ensure that the build is cross-platform.

## Actual behaviour

It's mandatory to add a `.cmd` extension at the end of all binary files of the list of the binaries into the Meson cross build definition file.

## Context

- OS Name: Windows10 22H2
- Node version: v18.16.0
- NPM version: v9.6.7
- XPM version: v0.15.2
- xPacks devDependencies:
  * "@xpack-dev-tools/meson-build": "0.63.3-1.1",
  * "@xpack-dev-tools/ninja-build": "1.11.1-2.1",
  * "@xpack-dev-tools/riscv-none-elf-gcc": "12.2.0-3.1"

**Comment by ilg-ul** [comment]
BTW, did you play with the [Hello World template](https://github.com/micro-os-plus/hello-world-qemu-template-xpack) to generate meson projects?

**Comment by pur-jus** [comment]
No, before today I didn't play with your great template! But now I understand the configuration strategy to have a cross-platform project 😃 

[package.json](https://github.com/micro-os-plus/hello-world-qemu-template-xpack/blob/d96fab6f592803b3118e864fdf26521974163944/assets/sources/package-liquid.json#L106):
```json
"commandMesonPrepareCross": "meson setup --backend ninja --buildtype {{ properties.buildType }} -D platform-name={{ properties.platformName }} --cross xpacks/micro-os-plus-build-helper/meson/toolchains/{{ properties.toolchainFileName }} --cross platform-{{ properties.platformName }}/meson/cross.ini {{ properties.buildFolderRelativePathPosix }} .",
```

> I suggest you register a ticket to meson and ask for this feature (https://github.com/mesonbuild/meson/issues).

I'm fairly new to Meson, therefore, I'm not sure that I have the knowledges and great explanation to expose the problem within Meson project. 👶 

Again thank you for your job! 👍

**Comment by ilg-ul** [comment]
> I'm not sure that I have the knowledges and great explanation to expose the problem within Meson project

You can do it. I will ack the issue and support you. Just be sure you mention that the problem affects all projects which have dependencies installed with npm/xpm (both!).

**Comment by pur-jus** [comment]
> > I'm not sure that I have the knowledges and great explanation to expose the problem within Meson project
> 
> You can do it. I will ack the issue and support you. Just be sure you mention that the problem affects all projects which have dependencies installed with npm/xpm (both!).

It's done ([#11827](https://github.com/mesonbuild/meson/issues/11827)). I hope that it is clear 🤞
