### ISSUE TITLE
Change linux default path

### ISSUE THREAD

**Issue by LnnrtS** [xpack/xpm-js#60]
## Is your feature request related to a problem?

visible folder gets created in home directory

## Describe the solution you'd like

Use `$HOME/.xpack` instead of `$HOME/opt/xpack`

## Describe alternatives you've considered

Use another existing directory in the home folder

**Comment by ilg-ul** [comment]
You can relocate the xPack folder wherever you like by defining environment variables, see https://xpack.github.io/xpm/folders/.

What is wrong with `~/opt`? It is the local equivalent of `/opt`, which according to the [Filesystem Hierarchy Standard](http://www.pathname.com/fhs/pub/fhs-2.3.html),  "is reserved for the installation of add-on application software packages".

**Comment by LnnrtS** [comment]
Sorry, I answered that via email reply some time ago but it never got here. Here's what I wrote:

I have seen this, but I still think the default should be the best possible one.

The problem with `~/opt` is that no other app is using it (most of them, also `npm`, use a hidden folder in the home root) and adding another visible folder directly in the home directory feels intrusive (you are scanning the folder to navigate and additional noise there is distracting).

**Comment by ilg-ul** [comment]
I'll soon restart work on xpm, and I'd like this sorted out.

As far as I can tell, the new recommendation is to put all local files in `$HOME/.local`.

How about `$HOME/.local/xPacks`? It is somehow consistent with `$HOME/.cache/xPacks`, already in use.

**Comment by LnnrtS** [comment]
> How about `$HOME/.local/xPacks`?

Sounds good to me!

**Comment by ilg-ul** [comment]
I suggest the following rules:

- ask the user if ok to move `opt/xPacks` to `.local/xPacks`; if the user rejects it, remember this and never ask again
- if `$HOME/.local/xPacks` exists, use it
- else if `$HOME/opt/xPacks` exists, use it
- otherwise create `$HOME/.local/xPacks` and use it

What do you think?

**Comment by LnnrtS** [comment]
What about this?
- If `opt/xPacks` exists and `.local/xPacks` doesn't, move everything and create a symlink
- else If `opt/xPacks` doesn't exist and `.local/xPacks` does, do nothing
- else do some error handling, involving the user if needed

**Comment by ilg-ul** [comment]
In other words move and leave a link in the old place, without any user interaction? 

Seems simpler. Why not?

**Comment by LnnrtS** [comment]
Yes, that's what I wanted to say :)

**Comment by ilg-ul** [comment]
Super!

I really appreciate your suggestions, it looks like I have a quite twisted mind and having someone with a clear mind to see the simple solutions is of great help. :-)

**Comment by LnnrtS** [comment]
Sometimes it's hard to see things when you are very close to them.

Thanks!

**Comment by ilg-ul** [comment]
This change currently awaits the new Eclipse release (Dec 16th), which was already updated to search in the new path.

After this I'll update xpm and make a new release.

**Comment by ilg-ul** [comment]
The new default on Linux is not `$HOME/.local/xpack`. At first run, the folder is renamed and a link is left behind.

**Comment by ilg-ul** [comment]
Fixed on 2021-01-25.
