### ISSUE TITLE
xpm run does not always react to signals (ctrl + c)

### ISSUE THREAD

**Issue by LnnrtS** [xpack/xpm-js#82]
## To Reproduce

xpm run hangs in qemu (hard fault).  
Pressing ctrl + c does not terminate the process

## Context

debian 10  
zsh

**Comment by ilg-ul** [comment]
I confirm, signal processing is not implemented yet.

But please be aware that QEMU too has some issues with intercepting signals.

**Comment by ilg-ul** [comment]
I checked and the problem seems indeed specific to QEMU, since a Ctrl C during build ended properly:

```console
> cmake --build build/stm32f4discovery-cmake-gcc10-debug
[0/2] Re-checking globbed directories...
[30/97] Building CXX object CMakeFiles/application.dir/Users/ilg/My_Files/WKS_...udy-projects.git/blinky-rtos/xpacks/micro-os-plus-rtos/src/rtos/clocks.cpp.ob^C
ninja: build stopped: interrupted by user.
```

If there will be any non-QEMU cases, we'll reconsider, but for now there is not much we can do.
